// benchmarks/suites/memory/solidjs/suite.js
// benchmarks/suites/memory/solidjs/suite.js — Memory Benchmark (SolidJS)
//
// Thin wrapper around engine/memory.js measureMemoryProfile.
// Defines the SolidJS-specific create/destroy lifecycle using createRoot +
// createVList, and formats results with rating thresholds.
//
// Chrome-only (requires performance.memory API).

import { createRoot, createSignal } from "solid-js";
import { createVList } from "vlist-solidjs";
import { createVListFromConfig } from "vlist/config";
import {
  defineSuite,
  generateItems,
  benchmarkTemplate,
  round,
  rateLower,
} from "../../../runner.js";
import { ITEM_HEIGHT } from "../../../engine/constants.js";
import { measureMemoryProfile, scrollWithSetter } from "../../../engine/memory.js";
import { findViewport } from "../../../engine/viewport.js";
import { loadSynthetic } from "../../../engine/synthetic.js";
import { scrollCapturePlugin } from "../../../engine/logical-scroll.js";
import { formatMemoryMetrics } from "../format.js";

// =============================================================================
// Suite
// =============================================================================

defineSuite({
  id: "memory-solidjs",
  name: "Memory (SolidJS)",
  description:
    "Heap usage after render and after 10s of scrolling — reveals leaks and GC pressure",
  icon: "🧠",

  run: async ({ itemCount, container, onStatus }) => {
    const items = generateItems(itemCount);

    const result = await measureMemoryProfile({
      container,
      createFn: async () => {
        // createRoot establishes a proper reactive ownership scope so that
        // createVList's onMount, onCleanup, and createEffect calls are correctly
        // owned and will be disposed when dispose() is called.
        let dispose;
        createRoot((d) => {
          dispose = d;

          const [config] = createSignal({
            items,
            item: {
              height: ITEM_HEIGHT,
              template: benchmarkTemplate,
            },
            scroll: { mode: "native" },
          });

          const { setRef } = createVList(config);

          const el = document.createElement("div");
          el.style.cssText = "height:100%;width:100%;";
          container.appendChild(el);
          setRef(el);
        });

        return { instance: dispose };
      },
      destroyFn: (dispose) => dispose(),
      onStatus,
    });

    // ── Handle unavailable API ─────────────────────────────────────────
    if (!result.available) {
      return [
        {
          label: "Status",
          value: 0,
          unit: "",
          better: "lower",
          rating: "ok",
          _note:
            "performance.memory unavailable — use Chrome with --enable-precise-memory-info",
        },
      ];
    }

    // ── Format metrics ─────────────────────────────────────────────────
    const { renderDeltaMB, scrollDeltaMB, afterRenderMB, totalDeltaMB } =
      result;

    // Thresholds similar to Svelte (action-based, minimal framework overhead)
    const scrollLeakGood = itemCount <= 100_000 ? 1 : 3;
    const scrollLeakOk = itemCount <= 100_000 ? 5 : 10;

    // Render heap thresholds (MB)
    const renderGood = itemCount <= 10_000 ? 5 : itemCount <= 100_000 ? 15 : 80;
    const renderOk = itemCount <= 10_000 ? 15 : itemCount <= 100_000 ? 40 : 200;

    return [
      {
        label: "After render",
        value: round(renderDeltaMB, 2),
        unit: "MB",
        better: "lower",
        rating: rateLower(renderDeltaMB, renderGood, renderOk),
      },
      {
        label: "Scroll delta",
        value: round(scrollDeltaMB, 2),
        unit: "MB",
        better: "lower",
        rating: rateLower(
          Math.abs(scrollDeltaMB),
          scrollLeakGood,
          scrollLeakOk,
        ),
      },
      {
        label: "Total heap",
        value: round(afterRenderMB, 1),
        unit: "MB",
        better: "lower",
      },
      {
        label: "Total delta",
        value: round(totalDeltaMB, 2),
        unit: "MB",
        better: "lower",
      },
    ];
  },
});

if (__BENCH_HAS_SYNTHETIC__) defineSuite({
  id: "memory-synthetic-solidjs",
  name: "Memory (SolidJS)",
  description: "Heap of a synthetic list created through the SolidJS adapter, after render and after scrolling its position",
  icon: "🧠",
  run: async ({ itemCount, container, onStatus, intensity }) => {
    await loadSynthetic(createVListFromConfig);
    const items = generateItems(itemCount);
    const capture = { current: null };
    const result = await measureMemoryProfile({
      container,
      createFn: async () => {
        let dispose;
        createRoot((done) => {
          dispose = done;
          const [config] = createSignal({
            items,
            item: { height: ITEM_HEIGHT, template: benchmarkTemplate },
            scroll: { mode: "synthetic" },
            plugins: [scrollCapturePlugin((set) => { capture.current = set; })],
          });
          const { setRef } = createVList(config);
          const el = document.createElement("div");
          el.style.cssText = "height:100%;width:100%;";
          container.appendChild(el);
          setRef(el);
        });
        return { instance: dispose };
      },
      destroyFn: (dispose) => dispose(),
      scrollFn: (durationMs, speedPxPerFrame, onProgress) => {
        const viewport = findViewport(container);
        const content = container.querySelector(".vlist-content");
        return scrollWithSetter({
          max: items.length * ITEM_HEIGHT - viewport.clientHeight,
          set(position) {
            if (!capture.current) throw new Error("SolidJS list did not install the scroll writer");
            capture.current(position);
            if (viewport.scrollTop !== 0 || content.scrollTop !== 0) {
              throw new Error("Synthetic memory scroll moved a native main-axis scroll offset");
            }
          },
        }, durationMs, speedPxPerFrame, onProgress);
      },
      onStatus,
      ...(intensity?.memoryScrollMs && { scrollDurationMs: intensity.memoryScrollMs }),
    });
    return formatMemoryMetrics(result, {
      scrollLeakGood: itemCount <= 100_000 ? 1 : 3,
      scrollLeakOk: itemCount <= 100_000 ? 5 : 10,
      renderGood: itemCount <= 10_000 ? 5 : itemCount <= 100_000 ? 15 : 80,
      renderOk: itemCount <= 10_000 ? 15 : itemCount <= 100_000 ? 40 : 200,
    });
  },
});

// benchmarks/suites/scrollto/react/suite.js
// benchmarks/suites/scrollto/react/suite.js — scrollToIndex Benchmark (React)
//
// Thin wrapper around engine/scrollto.js measureScrollToPerformance.
// Defines the React create/destroy lifecycle and formats results with
// rating thresholds (more lenient for React overhead).

import { createRoot } from "react-dom/client";
import { useVList } from "vlist-react";
import { createVListFromConfig } from "vlist/config";
import {
  defineSuite,
  generateItems,
  benchmarkTemplate,
  waitFrames,
  tryGC,
  rateLower,
} from "../../../runner.js";
import { ITEM_HEIGHT } from "../../../engine/constants.js";
import { findViewport } from "../../../engine/viewport.js";
import { measureScrollToPerformance } from "../../../engine/scrollto.js";
import { loadSynthetic } from "../../../engine/synthetic.js";

// =============================================================================
// React Component
// =============================================================================

let listApiRef = null;

function BenchmarkList({ items, target, mode }) {
  const vlistApi = useVList({
    items,
    item: {
      height: ITEM_HEIGHT,
      template: benchmarkTemplate,
    },
    scroll: { mode },
  });

  vlistApi.containerRef.current = target;
  listApiRef = vlistApi;

  return null;
}

// =============================================================================
// Suite
// =============================================================================

defineSuite({
  id: "scrollto-react",
  name: "scrollToIndex (React)",
  description:
    "Latency of smooth scrollToIndex() — time from call to scroll settled",
  icon: "🎯",

  run: async ({ itemCount, container, onStatus }) => {
    const items = generateItems(itemCount);

    // ── Create React component ─────────────────────────────────────────
    container.innerHTML = "";
    listApiRef = null;

    const root = createRoot(container);
    root.render(<BenchmarkList items={items} target={container} mode="native" />);

    // Let initial render settle — React needs extra frames
    await waitFrames(15);

    const viewport = findViewport(container);

    if (!viewport || !listApiRef) {
      root.unmount();
      container.innerHTML = "";
      throw new Error("Could not find vlist viewport element or API");
    }

    const instance = listApiRef.getInstance();
    if (!instance) {
      root.unmount();
      container.innerHTML = "";
      throw new Error("Could not get vlist instance from React adapter");
    }

    // ── Measure with engine ────────────────────────────────────────────
    const result = await measureScrollToPerformance({
      viewport,
      scrollToFn: (index, align) => instance.scrollToIndex(index, align),
      itemCount,
      onStatus,
    });

    // ── Clean up ───────────────────────────────────────────────────────
    root.unmount();
    container.innerHTML = "";
    listApiRef = null;
    await tryGC();

    // ── Format results ─────────────────────────────────────────────────
    // Thresholds adjusted for React overhead (more lenient)
    const goodThreshold = itemCount <= 100_000 ? 500 : 700;
    const okThreshold = itemCount <= 100_000 ? 1000 : 1400;

    return [
      {
        label: "Median",
        value: result.median,
        unit: "ms",
        better: "lower",
        rating: rateLower(result.median, goodThreshold, okThreshold),
      },
      {
        label: "Min",
        value: result.min,
        unit: "ms",
        better: "lower",
        rating: rateLower(result.min, goodThreshold, okThreshold),
      },
      {
        label: "p95",
        value: result.p95,
        unit: "ms",
        better: "lower",
        rating: rateLower(result.p95, goodThreshold * 1.5, okThreshold * 1.5),
      },
      {
        label: "Max",
        value: result.max,
        unit: "ms",
        better: "lower",
        rating: rateLower(result.max, goodThreshold * 2, okThreshold * 2),
      },
    ];
  },
});

if (__BENCH_HAS_SYNTHETIC__) defineSuite({
  id: "scrollto-synthetic-react",
  name: "scrollToIndex (React)",
  description: "Latency of scrollToIndex() in synthetic mode, through the React adapter",
  icon: "🎯",
  run: async ({ itemCount, container, onStatus }) => {
    await loadSynthetic(createVListFromConfig);
    const items = generateItems(itemCount);
    container.innerHTML = "";
    listApiRef = null;
    const root = createRoot(container);
    root.render(<BenchmarkList items={items} target={container} mode="synthetic" />);
    try {
      await waitFrames(15);
      const viewport = findViewport(container);
      const instance = listApiRef?.getInstance();
      const content = container.querySelector(".vlist-content");
      if (!viewport || !instance) throw new Error("Could not get the synthetic React list");
      const result = await measureScrollToPerformance({
        viewport,
        scrollToFn: (index, align) => instance.scrollToIndex(index, align),
        readPosition: () => instance.getScrollPosition(),
        itemCount,
        onStatus,
      });
      if (viewport.scrollTop !== 0 || content.scrollTop !== 0) {
        throw new Error("Synthetic scrollToIndex moved a native main-axis scroll offset");
      }
      const goodThreshold = itemCount <= 100_000 ? 500 : 700;
      const okThreshold = itemCount <= 100_000 ? 1000 : 1400;
      return [
        { label: "Median", value: result.median, unit: "ms", better: "lower", rating: rateLower(result.median, goodThreshold, okThreshold) },
        { label: "Min", value: result.min, unit: "ms", better: "lower", rating: rateLower(result.min, goodThreshold, okThreshold) },
        { label: "p95", value: result.p95, unit: "ms", better: "lower", rating: rateLower(result.p95, goodThreshold * 1.5, okThreshold * 1.5) },
        { label: "Max", value: result.max, unit: "ms", better: "lower", rating: rateLower(result.max, goodThreshold * 2, okThreshold * 2) },
      ];
    } finally {
      root.unmount();
      container.innerHTML = "";
      listApiRef = null;
    }
  },
});
